export const TodoActionTypes = {
  ADD_TODO: "ADD_TODO",
  REMOVE_TODO: "REMOVE_TODO",
  EDIT_TODO: "EDIT_TODO",
  UPDATE_TODO: "UPDATE_TODO",
  TOGGLE_ADD_TODO_DIALOG: "TOGGLE_ADD_TODO_DIALOG",
  CANCEL_TODO_EDIT: "CANCEL_TODO_EDIT",
  TOGGLE_COMPLETE_TODO: "TOGGLE_COMPLETE_TODO",
};
